name: win32_websocket
description: A Dart WebSocket library using Windows WinHTTP API.
version: 0.0.1
repository: https://github.com/Win32WebSocket/win32_websocket

environment:
  sdk: ^3.0.0

dependencies:
  ffi: ^2.1.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
